name: Build zip and upload to ESO UI
on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
            with:
              #Folder that should live inside the zip, probably should match add-on name
              path: 'InkTracker'
        
          #Zips the release, excluding .git* and .vscode files
          - name: 'Zip release'
            run: 7z a InkTracker.zip * -xr!*.git* -xr!*.vscode*

          #Optional: Attaches the generated zip to the GitHub release (before uploading to ESO UI)
          - name: 'Attach zip to release'
            uses: Shopify/upload-to-release@v2.0.0
            with:
              name: InkTracker.zip
              path: InkTracker.zip
              repo-token: ${{ secrets.GITHUB_TOKEN }}

          - name: 'ESO UI Publish'
            uses: lastguest/esoui-deploy-action@main
            with:
              #Inside the folder configured above, this should be the add-on definition txt file (that has Title, Description, files, ect.)
              addon-file-path: ./InkTracker/InkTracker.txt 
              #Match generated zip file name above
              upload-zip-path: InkTracker.zip
              #Add-on ID from ESO UI
              addon-id: 3924 
              #ESO UI API Key, should be stored in GitHub secrets
              eso-ui-api-key: ${{secrets.ESOUI_API_TOKEN}}
              github-api-key: ${{secrets.GITHUB_TOKEN}}
              #Optional: If true will hit the update test URL, rather than doing an actual update to the add-on
              test-only: true
