name: Build zip and upload to ESO UI
on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
            with:
              #Folder that should live inside the zip, probably should match add-on name
              path: 'InkTracker'
        
          #Zips the release, excluding .git* and .vscode files
          - name: 'Zip release'
            run: 7z a InkTracker.zip * -xr!*.git* -xr!*.vscode*

          - name: 'ESO UI Publish'
            run: cd InkTracker && ls -la
          
